Dynamo persistance
oaplatform/oap-storage pull request #3
Opened 2022-05-16 13:22 UTC by JuliaGalabut

2022-05-17 14:13 UTC, alebastrov approved these changes

2022-05-24 11:11 UTC, vovakyrychenko requested changes

2022-05-24 11:11 UTC, vovakyrychenko commented on oap-storage-dynamo/src/test/java/oap/storage/dynamo/TestUtil.java
> +    public static void setEnv( String key, String value ) {
@see oap.system.Env

2022-05-25 09:44 UTC, JuliaGalabut commented on oap-storage-dynamo/src/test/java/oap/storage/dynamo/TestUtil.java
> +    public static void setEnv( String key, String value ) {
changed

2022-07-11 10:46 UTC, merged